
version: '2'
services:

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    container_name: esac_database
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"


  # The Application
  app:
    build:
      context: ""
      dockerfile: ../local_app.dockerfile
    working_dir: /var/www
    container_name: esac_application
    volumes:
      - ../:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - 80:8000
    depends_on:
      - "database"

volumes:
  dbdata: